name: 1.0.0$(Rev:.r) #Build number

#Build variables
variables:
  App.Home: $(Build.SourcesDirectory)/Apps/WebClient
  App.Name: webclient

trigger:
 batch: 'true'
 branches:
   include:
     - dev
 paths:
   include:
     - Apps/WebClient
 
pool:
  name: 'HealthGateway'

steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(App.Home)/src'
    
- task: DotNetCoreCLI@2
  inputs:
    modifyOutputPath: false
    command: 'publish'
    publishWebProjects: false
    projects: '$(App.Home)/src'
    arguments: '-o $(Build.BinariesDirectory)'
    zipAfterPublish: false

- script: |
    dotnet tool install --global dotnet-sonarscanner --version 4.6.2
    dotnet sonarscanner begin /k:"webclient_dev" /d:sonar.host.url="https://sonarqube-q6qfzk-tools.pathfinder.gov.bc.ca" /d:sonar.coverage.exclusions="**Tests*.cs" /d:sonar.login="70a09cf96a40f256e999ecfa7a59359f06167b16" /d:sonar.testExecutionReportPaths="jest.out/test-report.xml" /d:sonar.typescript.lcov.reportsPaths="jest.out/lcov.info"
    dotnet build
    dotnet sonarscanner end /d:sonar.login="70a09cf96a40f256e999ecfa7a59359f06167b16" > $(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).txt
    displayName: 'Perform static analisis'
#- script: |
#    pushd $(App.Home)
#    cp Dockerfile $(Build.BinariesDirectory)
#    pushd src
#    dotnet publish -o $(Build.BinariesDirectory)
#    popd
#    popd
#  displayName: 'Restore and publish .Net App'

- script: |
    cp $(App.Home)/Dockerfile $(Build.BinariesDirectory)
    oc process -f $(Build.SourcesDirectory)/Tools/BaseBuild/build.yaml -p NAME=$(App.Name) | oc apply -f -
    oc start-build $(App.Name) --wait --follow --from-dir $(Build.BinariesDirectory) 
    oc tag $(App.Name):latest $(App.Name):$(Build.BuildNumber)
    echo `date` > $(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).txt
  displayName: 'Build OpenShift Image and push to Image Stream'

- task: PublishPipelineArtifact@0
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'

