name: 1.0.0$(Rev:.r) #Build number

#Build variables
variables:
  App.Home: $(Build.SourcesDirectory)/Apps/WebClient

trigger:
 batch: 'true'
 branches:
   include:
     - dev
 paths:
   include:
     - Apps/WebClient
 
pool:
  name: 'HealthGateway'

steps:
- script: |
    pushd $(App.Home)
    cp Dockerfile $(Build.BinariesDirectory)
    pushd src
    dotnet publish -o $(Build.BinariesDirectory)
    popd
    popd
  displayName: 'Restore and publish .Net App'

- script: |
    oc start-build webclient-test --wait --follow --from-dir $(Build.BinariesDirectory) 
    oc tag webclient-test:latest webclient-test:$(Build.BuildNumber)
    echo `date` > $(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).txt
  displayName: 'Build OpenShift Image and push to Image Stream'

- task: PublishPipelineArtifact@0
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'

