name: 1.0.0$(Rev:.r) #Build number

#Build variables
variables:
  App.Home: $(Build.SourcesDirectory)/Apps/WebClient

trigger:
 batch: 'true'
 branches:
   include:
     - dev
 paths:
   include:
     - Apps/WebClient
 
pool:
  name: 'HealthGateway'

steps:
- script: |
    echo $(Build.BuildNumber)
    echo $PWD
    oc whoami
    oc start-build webclient-test --from-dir $(App.Home) --follow
  displayName: 'Stage 1'