# https://aka.ms/yaml
name: 1.0.0$(Rev:.r) #Build number

trigger:
 batch: 'true'
 branches:
   include:
     - dev
 paths:
   include:
     - Apps/WebClient
 
pool:
  name: 'HealthGateway'

steps:
- script: |
    echo $(Build.BuildNumber)
    echo $PWD
    oc whoami
    oc start-build webclient-test --from-dir $(Build.SourcesDirectory) --follow
  displayName: 'Stage 1'