# https://aka.ms/yaml
name: 1.0.0$(Rev:.r) #Build number

trigger:
 batch: 'true'
 branches:
   include:
     - dev
 paths:
   include:
     - Apps/WebClient
 
pool:
  name: 'HealthGateway'

steps:
- script: |
    echo $(Build.BuildNumber)
    oc whoami
  displayName: 'Stage 1'

- script: oc start-build webclient-test --from-dir . --follow
  displayName: 'Initiate OpenShift build'