properties:
  sonar.coverage.exclusions: '**Tests*.cs'
  sonar.testExecutionReportPaths: src/jest.out/test-report.xml
  sonar.typescript.lcov.reportPaths: jest.out/lcov.info
  sonar.cs.opencover.reportsPaths: '**/coverage.opencover.xml'
  sonar.cs.xunit.reportsPaths: '**/xUnitResults/results.xml'
test-runners:
  - xunit
  - jest 
