apiVersion: v1
kind: Template
metadata:
  name: healthgateway-template
  creationTimestamp: null
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 2
    selector:
      deploymentconfig: ${APP_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
        post:
          execNewPod:
            command:
              - curl
              - '-X'
              - POST
              - '-H'
              - 'Content-Type: application/json'
              - '--data'
              - '{"text": "New Version Deployed to **${ENV}** [Check it out!](https://${ENV}.gateway.health.pathfinder.gov.bc.ca) :rocket:"}'
              - https://chat.pathfinder.gov.bc.ca/hooks/pLdurJfnQ2EQgmbT9/PtFJ77rC2vZRjycwXgJYnDcQEkH8emtu97jdxHXJke4mCjuo
            containerName: webclient
          failurePolicy: Ignore
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - env:
          - name: IMMUNIZATION_URL
            value: http://immunization:8080/
          - name: IMMUNIZATION_VERSION
            value: v1/
          - name: IMMUNIZATION_PATH
            value: api/Fhir/
          imagePullPolicy: Always
          name: ${APP_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /${APP_NAME}/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: ${IMAGE}
          namespace: ${TOOLS_NAMESPACE}
      type: ImageChange
    - type: ConfigChange
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: null
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    maxReplicas: 4
    minReplicas: 2
    scaleTargetRef:
      apiVersion: v1
      kind: DeploymentConfig
      name: ${APP_NAME}
    targetCPUUtilizationPercentage: 70
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    host: ${ENV}-gateway.pathfinder.gov.bc.ca
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP
parameters: 
  - name: TOOLS_NAMESPACE
    displayName: Tools Project Namespace
    description: The namespace of the tools project
    value: q6qfzk-tools
    required: true 
  - name: ENV
    displayName: Enviroment
    description: The environment to be deployed to
    value: dev
    required: true 
  - name: APP_NAME
    displayName: App Name
    description: The name of the application
    value: webclient
    required: true 
  - name: IMAGE
    displayName: ImageStream:Tag
    description: The ImageStream plus the Tag to look for
    value: webclient:<TAG>
    required: true         